apiVersion: v1
kind: Service
metadata:
  name: user-onboarding
spec:
  selector:
    app: user-onboarding
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Matches the container port
  type: ClusterIP # Use LoadBalancer if exposing externally
